package com.norswap.autumn.parsing.state;

import com.norswap.autumn.parsing.state.CustomState.Inputs;
import com.norswap.autumn.parsing.state.CustomState.Result;

/**
 * Interface to be implemented by changes generated by a {@link CustomState} object.
 */
public interface CustomChanges
{
    ////////////////////////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new custom result object from these changes and the passed custom inputs.
     */
    Result result(Inputs inputs);

    ////////////////////////////////////////////////////////////////////////////////////////////////
}
